name: uoc-vscode
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - chardet
  - flake8
  - ipykernel
  - matplotlib
  - numpy
  - pandas
  - pip
  - pycodestyle
  - python=3.11
  - pip:
      - pycodestyle-magic