name: uoc-vscode
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - chardet
  - flake8
  - ipykernel
  - matplotlib
  - numpy
  - openpyxl
  - pandas
  - pip
  - pycodestyle
  - python=3.13
  - pip:
      - line-profiler
      - pycodestyle-magic
      - python-docx
